# =============================================================================
# GitHub Secret Scanning Configuration - Notification Service
# =============================================================================
# This file configures which paths and patterns should be excluded from
# GitHub's secret scanning to avoid false positives on sample/test data.

# Paths to exclude from secret scanning
paths-ignore:
  # Database sample/seed data - contains mock notification templates and data
  - 'database/data/**'
  - 'database/migrations/**'
  - 'database/seeds/**'

  # Test fixtures and mock data
  - 'tests/fixtures/**'
  - 'tests/mocks/**'
  - 'tests/__fixtures__/**'

  # Documentation and examples
  - 'docs/**'
  - 'examples/**'
  - '*.md'
  - '**/*.md'

  # Build artifacts and dependencies
  - 'node_modules/**'
  - 'dist/**'
  - 'build/**'
  - 'coverage/**'
  - '*.log'
  - 'logs/**'

  # Configuration templates and examples
  - '*.example'
  - '**/*.example'
  - '.env.example'
  - 'config/examples/**'

# File patterns to exclude
patterns-ignore:
  # Sample/test configuration files
  - '*.sample.*'
  - '*.template.*'
  - '*.example.*'

  # Test and mock files
  - '*.test.*'
  - '*.spec.*'
  - '*.mock.*'
  - '**/test-*'
  - '**/mock-*'

  # Documentation files
  - 'README*'
  - 'CHANGELOG*'
  - 'LICENSE*'
  - 'CONTRIBUTING*'
  - 'CODE_OF_CONDUCT*'

# Additional exclusions for notification service
file-types-ignore:
  # TypeScript test files
  - 'tests/**/*.ts'
  - 'tests/**/*.js'
  - 'src/**/*.test.ts'
  - 'src/**/*.spec.ts'

  # JSON files in data directories (notification templates, sample data)
  - 'database/**/*.json'
  - 'data/**/*.json'
  - 'fixtures/**/*.json'
  - 'templates/**/*.json'

  # Email template files
  - 'templates/**/*.html'
  - 'templates/**/*.txt'
  - 'email-templates/**'

  # Configuration files in test directories
  - 'tests/**/*.json'
  - 'tests/**/*.yml'
  - 'tests/**/*.yaml'

  # TypeScript configuration and build files
  - 'tsconfig*.json'
  - 'jest.config.*'
  - 'eslint.config.*'
